---
# tasks file for wordpress-install

- name: Téléchargement de l'archive Wordpress
  become: yes
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Decompression de l'archive
  unarchive:
    remote_src: true
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/

- name: copie de cotre fichier wordpress.conf à la place de la conf par défaut
  template:
    src: "wordpress.conf.j2"
    dest: /etc/apache2/sites-available/000-default.conf

- name: gestion des droits sur html
  file:
    path: /var/www/html
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
    mode: '0755'

- name: ajout du fichier wp-config
  template:
    src: "wp-config.php.j2"
    dest: "/var/www/html/wordpress/wp-config.php"

- name:  rechargement Apache2
  service:
    name: apache2
    state: restarted